# .streamlit/secrets.toml

[conntctions.snowflake]
account = "xxx"
user = "gracelisql99"
password = "xxxxx"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database ="SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
