# .streamlit/secrets.toml

[conntctions.snowflake]
account = "ZRMCDIW-SJB66490"
user = "gracelisql99"
password = "1126lwDH@@"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
